In [1]:
import pandas as pd
import numpy as np

In [2]:
companions_original = pd.read_csv('Mugrauer2018_table4.csv')
companions = companions_original.copy()

In [3]:
# remove spaces, dashes, star name
companions['Companion'] = companions['Companion'].map(lambda name: name.replace(' BC', 'B'))
companions['Companion'] = companions['Companion'].map(lambda name: name.replace(' AB', 'A'))
companions['Companion'] = companions['Companion'].map(lambda name: name.replace(' ', ''))
companions['Companion'] = companions['Companion'].map(lambda name: name.replace('-', ''))
companions['Companion'] = companions['Companion'].map(lambda name: name.replace('(EB)', ''))
companions['Companion'] = companions['Companion'].map(lambda name: name.replace('(SB)', ''))
companions['Companion'] = companions['Companion'].map(lambda name: name[:-1])

In [6]:
planets_original = pd.read_csv('exoplanet_archive_data.csv')
planets = planets_original.copy()

In [7]:
planets['pl_hostname'] = planets['pl_hostname'].map(lambda name: name.replace(' ', ''))
planets['pl_hostname'] = planets['pl_hostname'].map(lambda name: name.replace('-', ''))

In [8]:
companions_with_planets = []
for name in companions['Companion']:
    for planet_name in list(planets['pl_hostname']):
        if name==planet_name:
            companions_with_planets.append(name)
            break
            
planets_with_companions = []
for planet_hostname in planets['pl_hostname']:
    for companion_name in list(companions['Companion']):
        if companion_name==planet_hostname:
            planets_with_companions.append(planet_hostname)

In [9]:
# not sure why only 160 are in archive ??
print('Total companions: ', len(companions))
print('Total companions found in archive: ', len(companions_with_planets))
print('Total planets with companion stars: ', len(planets_with_companions))

Total companions:  207
Total companions found in archive:  160
Total planets with companion stars:  208

In [10]:
column_names = ['planet_host', 'planet_letter', 'discovery_method', 'sma', 'sma_err1', \
               'sma_err2', 'ecc', 'ecc_err1', 'ecc_err2', 'host_gmag', 'host_gmag_err', \
                'companion_mag', 'companion_mag_err', 'companion_sep']
df = pd.DataFrame(columns = column_names)

In [11]:
data = []
for companion in companions_with_planets:
    
    # get values for companion star
    companion_values = companions[companions['Companion']==companion].values[0]
    host_name = companion
    sep = float(companion_values[4]) # separation (AU)
    mag_str = companion_values[3].split('+') 
    comp_mag = float(mag_str[0]) # magnitude of companion
    comp_mag_err = float(mag_str[1]) # magnitude error of host

    # iterate over planet rows
    planet_rows = planets[planets['pl_hostname']==companion]
    for index,row in planet_rows.iterrows():
        letter = row['pl_letter']
        discovery_method = row['pl_discmethod']
        sma = float(row['pl_orbsmax'])
        sma_err1, sma_err2 = float(row['pl_orbsmaxerr1']), float(row['pl_orbsmaxerr2'])
        ecc = float(row['pl_orbeccen'])
        ecc_err1, ecc_err2 = float(row['pl_orbeccenerr1']), float(row['pl_orbeccenerr2'])
        host_mag = float(row['gaia_gmag'])
        host_mag_err = float(row['gaia_gmagerr'])
        planet_dict = {'planet_host': companion, 
                       'planet_letter':letter, 
                       'discovery_method':discovery_method, 
                       'sma':sma,
                       'sma_err1':sma_err1, 
                       'sma_err2':sma_err2,
                       'ecc':ecc, 
                       'ecc_err1':ecc_err1, 
                       'ecc_err2':ecc_err2, 
                       'host_gmag':host_mag, 
                       'host_gmag_err':host_mag_err, 
                       'companion_mag':comp_mag, 
                       'companion_mag_err':comp_mag_err, 
                       'companion_sep':sep}
        data.append(planet_dict)

In [14]:
df_final = df.append(data,True)

In [15]:
df_final

,planet_host,planet_letter,discovery_method,sma,sma_err1,sma_err2,ecc,ecc_err1,ecc_err2,host_gmag,host_gmag_err,companion_mag,companion_mag_err,companion_sep
0,HD142,b,Radial Velocity,1.02000,0.03000,-0.03000,0.170,0.060,-0.060,5.565,NaN,8.195,0.202,102.0
1,HD142,c,Radial Velocity,6.80000,0.50000,-0.50000,0.210,0.070,-0.070,5.565,NaN,8.195,0.202,102.0
2,WASP26,b,Transit,NaN,NaN,NaN,0.000,NaN,NaN,10.994,NaN,6.669,0.302,3916.0
3,WASP1,b,Transit,0.03889,0.00053,-0.00073,0.000,NaN,NaN,11.535,NaN,9.671,0.492,1820.0
4,WASP45,b,Transit,0.03963,0.00114,-0.00112,NaN,NaN,NaN,12.049,NaN,12.111,0.168,929.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,HATP1,b,Transit,0.05561,0.00082,-0.00083,NaN,NaN,NaN,10.179,NaN,3.066,0.174,1800.0
204,HD220842,b,Radial Velocity,0.74000,0.01800,-0.01800,0.404,0.009,-0.009,7.834,NaN,12.355,0.324,340.0
205,HIP116454,b,Transit,NaN,NaN,NaN,0.200,0.070,-0.070,9.932,NaN,12.911,0.193,524.0
206,WASP8,b,Transit,NaN,NaN,NaN,0.310,0.000,0.000,9.612,NaN,8.621,0.871,407.0
207,WASP8,c,Radial Velocity,5.28000,0.63000,-0.34000,0.000,0.000,0.000,9.612,NaN,8.621,0.871,407.0

In [16]:
#df_final.to_csv('table.csv', index=False)